language: scala
sudo: true
services:
  - docker

# make comparing to origin/master work and fetch full history for correct current and previous version detection
git:
  depth: 500

before_install:
  # using jabba for custom jdk management
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | bash && . ~/.jabba/jabba.sh

# default script for jobs, that do not have any specified
script:
  - jabba install ${JDK:=adopt@~1.8-0}
  - jabba use ${JDK:=adopt@~1.8-0}
  - java -version
  - sbt -jvm-opts .jvmopts-travis "$CMD"

jobs:
  include:
    - stage: check
      env: CMD="verifyCodeStyle"
      name: "Code style check. Run locally with: sbt verifyCodeStyle"
    - env: CMD="Test/compile"
      name: "Compile all code with 2.13"
    - env: CMD="unidoc; docs/paradox"
      name: "Create API and reference documentation"

    - stage: test
      env:
        - CMD="test"
      name: "Run tests with Scala 2.13 and AdoptOpenJDK 8"
    - env:
        - JDK="adopt@~1.11-0"
        - _JAVA_OPTIONS="-XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler"
        - CMD="test"
      name: "Run tests with Scala 2.13 and AdoptOpenJDK 11"

    - stage: whitesource
      name: WhiteSource
      script: git branch -f "$TRAVIS_BRANCH" && git checkout "$TRAVIS_BRANCH" && sbt -jvm-opts .jvmopts-travis whitesourceCheckPolicies whitesourceUpdate

    - stage: publish
      env: CMD="publish"
      name: "Publish artifacts to Bintray"


stages:
  # runs on master commits and PRs
  - name: check
    if: NOT tag =~ ^v

  # runs on master commits and PRs
  - name: test
    if: NOT tag =~ ^v

  # runs on main repo master commits and version-tagged commits
  - name: whitesource
    if: repo = akka/akka-projection AND ( ( branch = master AND type = push ) OR tag =~ ^v)

  # runs on main repo master commits and version-tagged commits
  - name: publish
    if: repo = akka/akka-projection AND ( ( branch = master AND type = push ) OR tag =~ ^v )

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot
   - $HOME/.sbt/launchers
   - $HOME/.cache/coursier
   - $HOME/.jabba/jdk

env:
  global:
  # encrypt with: travis encrypt --pro WHITESOURCE_PASSWORD=...
  - secure: "viFrZz1ODA9xUHGsxoRmF4hXwZjiIT7esLPr+xCqXCtBFEbvj09T6Y30xW8oYJcKBhh17Nm1thXhHvGjpM5CGlph1w9uTcAKrLjiblA1Ok6SVx2dBcg5aZfphvKkHglYgskeceSSpZH/9j+u9DTgKzZ3Hb1fj2o14YaYhjEr0fCfaa3yHgaVXjXMTFeaDLnHkmPkvehZUHSNhTniPMRDK2jt0sAib2y1PEUEEixY78rnkh1yP2fy2Qy6k2EpWgrtnRmn6pt/LidnEF7MHJrGjBQT6rZPAGJigeGNokiG7DbasBR39/wBPzm4OLH0tlYJA2fIx2fZuxfwIt8jNajJBKzwnzAaAm5JkHwVF8/oLbDr8rxR2r4AtQRSYhoCsCFDBZZm0jnZE87mvOof4DiTDlFWt4xqA/OQtzVhe8kS0PjmcYVyQYBvcQyrgmy+ARJKgNcZLFw2Qdq5APub8tnSHpTop6fBwt/vtzAzZzpspp6IvTX0bbRAqsEn/B3cG+HC8yN1eSIJ2b/zfqvCKBIU550hoSa6qpNa57flplYiZY7P0LAcj4Z2IeBrxC0Xhv77ercXCuS5cG7EStb3ZXXoR6TqIFmbmuSxIDV6IPm4bvuAvkeifo1amyZMns5pgL+1G0xdSnR7wsmFlTGi8prTE29CyFC4NnKa03eEF/PPqr8="
